# Welcome to numpy

In [1]:
import sys 
print(sys.version)

3.13.2 (v3.13.2:4f8bb3947cf, Feb  4 2025, 11:51:10) [Clang 15.0.0 (clang-1500.3.9.4)]


# THE MAIN 1D 2D 3D ARRAY 

In [3]:
import numpy as np
myarr = np.array([1,2,3,4,5,])
print(myarr)  #this is a 1D array
print("ndim =", myarr.ndim)  #1d of the array

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print("ndim =", arr2d.ndim)



arr3d = np.array([
  [[1, 2], [3, 4]],
  [[5, 6], [7, 8]]
])
print(arr3d)
print("ndim =", arr3d.ndim)

[1 2 3 4 5]
ndim = 1
[[1 2 3]
 [4 5 6]]
ndim = 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim = 3


In [14]:
import numpy as np
myarray = np.array([[1,2,3,4,5,6]], np.int64)
print(myarray) 
myarray.shape
myarray.dtype

[[1 2 3 4 5 6]]


dtype('int64')

In [35]:


import numpy as np
# myarr2 = np.array([1,2,4.65,6,7], np.float32)
# print(myarr2)
# myarr2.shape


#Creating a 2-D Array
#We can create a two dimensional (2-D) arrays by
#passing nested lists to the array() function.
# Observe that the integers 3, 7, 0 and -1 have been
#promoted to floats. 

arr3 = np.array([[2.4,3,8],[4.91,7,9],[0,-1,10]])
print(arr3.ndim)
print(arr3)

arr3.shape

arr3.itemsize # 3x3 matrix has 8 bytes per item it store float 64 bit each items...

arr3.size # 3x3 matrix has 9 items in it




2
[[ 2.4   3.    8.  ]
 [ 4.91  7.    9.  ]
 [ 0.   -1.   10.  ]]


9

# Zeros Ones Arrange Range 


In [ ]:
array4 = np.zeros((3,3),np.float32)
array4
#array4.itemsize #4


# array4 = np.array_equal(arr3, array4)
# print(array4) # False, because arr3 is not equal to array4

array5 = np.ones((3,3),np.float32)
print(array5)

array4 = np.array_equal(array4, array5)
print(array4) # True, because array4 is equal to array5


array6 = np.arange(1,10,2)
print(array6) # [1 3 5 7 9]
array7 = np.linspace(1,10,5)
print(array7) # [ 1.   3.25 5.5 7.75 10. ]
# Explanation of linspace::
#Step
# Value
# 0
# 1.00
# 1
# 1 + 2.25 = 3.25
# 2
# 3.25 + 2.25 = 5.5
# 3
# 5.5 + 2.25 = 7.75
# 4
# 7.75 + 2.25 = 10.0
# (10 - 1) / (5 - 1) = 9 / 4 = 2.25





[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
False
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


# THE TABLE WITH NAME AND SUBJECTS FROM ANY INDIVIDUAL STUDENTS ACCESS (NUMPY VERSION)

In [2]:
import numpy as np
marks = np.array([
                  [78,67,56],
                  [76,75,47],
                  [84,59,60],
                  [67,72,54]         
                  ])
# Marks of Vedika in English (row 1, col 1)
print(marks[1][1]) #output: 75
#FIRST ROW , SECOND COLUMN
print(marks[1][2]) #output: 47

# All Maths marks (first column)
print(marks[:, 0])  # Output: [78 76 84 67]

#all marks of HARUN
print(marks[2]) # Output: [84 59 60]


75
47
[78 76 84 67]
[84 59 60]


# SLICING OPERATIONS TRANSPOSE SORTING

In [ ]:
# Slicing the array
# We can slice the array to get a sub-array.
array6 = np.array([-2 , 2 ,6 , 8, 10])
print(array6[1:4])  # Output: [ 2  6  8]
print("ndim =", array6.ndim)  # Output: ndim = 1
print("shape =", array6.shape)  # Output: shape = (5,)
print("dtype =", array6.dtype)  # Output: dtype = int64
print("itemsize =", array6.itemsize)  # Output: itemsize = 8
print("size =", array6.size)  # Output: size = 5


# Reshaping the array
# We can reshape the array to change its dimensions.
array7 = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])
reshaped_array = array7.reshape(1, 9)  # Reshape to 1 row and 9 columns
print(reshaped_array)  # Output: [[1 2 3 4 5 6 7 8 9]]
print("ndim =", reshaped_array.ndim)  # Output: ndim = 2
print("shape =", reshaped_array.shape)  


#REVERSING THE ARRAY
reversed_array = array7[::-1]  # Reverse the array
print(reversed_array)  # Output: [[7 8 9] [4 5 6] [1 2 3]]


#Now let us see how slicing is done for 2-D arrays.
#For this, let us create a 2-D array called array9 having
#3 rows and 4 columns.

array9 = np.array([
                   [ -7, 0, 10, 20],
                   [ -5, 1, 40, 200],
                   [ -1, 1, 4, 30]
                    ])

array9[0:3,2] #0:3 → rows from index 0 to 2 (inclusive)
#2   → column index 2 (i.e., 3rd column)


#Stacking arrays
# We can stack arrays vertically or horizontally.
array10 = np.array([[1, 2], [3, 4]])
array11 = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((array10, array11))  # Vertical stacking
print(vertical_stack)  # Output: [[1 2] [3 4] [[5 6] [7 8]]
horizontal_stack = np.hstack((array10, array11))  # Horizontal stacking
print(horizontal_stack)  # Output: [[1 2 5 6] [3 4 7 8]]    


# Broadcasting
# Broadcasting allows us to perform operations on arrays of different shapes.
array12 = np.array([[1, 2], [3, 4]])
array13 = np.array([10, 20])  # 1D array
result = array12 + array13  # Broadcasting addition
print(result)  # Output: [[11 22] [13 24]]

# Saving and loading arrays
# We can save and load arrays to/from files.
np.save('my_array.npy', array12)  # Save array to file
loaded_array = np.load('my_array.npy')  # Load array from file
print(loaded_array)  # Output: [[1 2] [3 4]]

# Random number generation
# We can generate random numbers using NumPy.
random_array = np.random.rand(3, 3)  # Generate a 3x3 array of random numbers
print(random_array)  # Output: Random 3x3 array


# Statistical operations
# We can perform statistical operations on arrays.
mean_value = np.mean(array7)  # Calculate mean
print("Mean value:", mean_value)  # Output: Mean value: 5.0
std_value = np.std(array7)  # Calculate standard deviation
print("Standard deviation:", std_value)  # Output: Standard deviation: 2.581  


# Matrix operations
# We can perform matrix operations like multiplication.
array1 = np.array([[1, 2], [3, 4], [5, 6]])
array2 = np.array([[7, 8], [9, 10], [11, 12]])
print("Array 1:\n", array1)
print("Array 2:\n", array2)
array1 + array2  # Element-wise addition

array1 - array2  # Element-wise subtraction

array1 * array2  # Element-wise multiplication

array1 @ array2.T  # Matrix multiplication (dot product)
print("Matrix multiplication:\n", array1 @ array2.T)  # Output: [[13 16 19]
# [29 34 39]
# [45 52 59]]   


# Tranpose 

# Transposing an array turns its rows into columns and
# columns into rows just like matrices in mathematics. 
array3 = np.array([
    [10,-7,0, 20],
    [-5,1,200,40],
    [30,1,-1,4]
            ])
array3
array3.transpose() # Transpose the array

# Sorting an Array
array4 = np.array([3,1,4,2,5])
array4.sort()  # Sort the array in place
print("Sorted array:", array4)  # Output: Sorted array: [1 2 3 4 5]

array4 = np.array([
                   [10,-7,0,20], 
                   [-5,1,200,40],
                   [30,1,-1,4]
                   ])
print("Original array:\n", array4)
array4.sort(axis=0) # Sort along the first axis (columns)
print("Sorted array along columns:\n", array4)

array4.sort(axis=1) # Sort along the second axis (rows)
print("Sorted array along rows:\n", array4)  # Output: Sorted array along rows:
# [[-5 -7  0 20]
# [ 1  1  4 40]
# [10 30 200  4]]




[2 6 8]
ndim = 1
shape = (5,)
dtype = int64
itemsize = 8
size = 5
[[1 2 3 4 5 6 7 8 9]]
ndim = 2
shape = (1, 9)
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[11 22]
 [13 24]]
[[1 2]
 [3 4]]
[[0.32831535 0.01428426 0.0212936 ]
 [0.10574087 0.50418478 0.0390051 ]
 [0.03965546 0.406977   0.7269972 ]]
Mean value: 5.0
Standard deviation: 2.581988897471611
Array 1:
 [[1 2]
 [3 4]
 [5 6]]
Array 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]
Matrix multiplication:
 [[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
Sorted array: [1 2 3 4 5]
Original array:
 [[ 10  -7   0  20]
 [ -5   1 200  40]
 [ 30   1  -1   4]]
Sorted array along columns:
 [[ -5  -7  -1   4]
 [ 10   1   0  20]
 [ 30   1 200  40]]
Sorted array along rows:
 [[ -7  -5  -1   4]
 [  0   1  10  20]
 [  1  30  40 200]]


# Concatenating Arrays - It means Joining Two or More 2-D arrays either row-wise or column-wise

In [13]:
array1 = np.array([[10, 20], [-30, 40]])
array2 = np.zeros((2, 3), dtype=array1.dtype)

print("array1:\n", array1)
print("array2:\n", array2)

print("array1.shape:", array1.shape)
print("array2.shape:", array2.shape)

# For concatenation along rows (axis=0), columns must match
array2_row = np.zeros((1, 2), dtype=array1.dtype)
concat_rows = np.concatenate((array1, array2_row), axis=0)
print("Concatenate along rows:\n", concat_rows)

# For concatenation along columns (axis=1), rows must match
array2_col = np.zeros((2, 2), dtype=array1.dtype)
concat_cols = np.concatenate((array1, array2_col), axis=1)
print("Concatenate along columns:\n", concat_cols)

array1:
 [[ 10  20]
 [-30  40]]
array2:
 [[0 0 0]
 [0 0 0]]
array1.shape: (2, 2)
array2.shape: (2, 3)
Concatenate along rows:
 [[ 10  20]
 [-30  40]
 [  0   0]]
Concatenate along columns:
 [[ 10  20   0   0]
 [-30  40   0   0]]


# Reshaping Arrays


In [ ]:
array3 = np.arange(10,22)
array3

# Reshaping the array
array3.reshape(3, 4)  # Reshape to 3 rows and 4 columns
array3.reshape(2,6) # Reshape to 2 rows and 6 columns

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

# Spliting Array

In [28]:
# Splitting an array
# We can split an array into multiple sub-arrays.
array4 = np.array([
[ 10, -7, 0, 20],
[ -5, 1, 200, 40],
[ 30, 1, -1, 4],
[ 1, 2, 0, 4],
[ 0, 1, 0, 2]
])

array4

first,second,third = np.array_split(array4, [1,3])
print("First split:\n", first)  # Output: First split: [[10 -7 0 20]]
print("Second split:\n", second)  # Output: Second split: [[-5 1 200 40]
# [30 1 -1 4]]
print("Third split:\n", third)  # Output: Third split: [[1 2 0 4]
# [0 1 0 2]]    


firstc,secondc,thirdc = np.array_split(array4, [1,2], axis=1)
print("First split along columns:\n", firstc)  # Output: First split along

firstc, secondc, thirdc = np.array_split(array4, [1, 2], axis=0)
print("First split along rows:\n", firstc)  # Output: First split along

First split:
 [[10 -7  0 20]]
Second split:
 [[ -5   1 200  40]
 [ 30   1  -1   4]]
Third split:
 [[1 2 0 4]
 [0 1 0 2]]
First split along columns:
 [[10]
 [-5]
 [30]
 [ 1]
 [ 0]]
First split along rows:
 [[10 -7  0 20]]


# Statistical Operations on Array

In [37]:
arrayA = np.array([1,0,2,-3,6,8,4,7])
arrayB = np.array([[3,6], [4,2]])
arrayA.max() # Find the maximum value in arrayA
arrayA.min() # Find the minimum value in arrayA
arrayA.sum() # Find the sum of all elements in arrayA
arrayA.mean() # Find the mean of all elements in arrayA
arrayA.std() # Find the standard deviation of all elements in arrayA
arrayA.var() # Find the variance of all elements in arrayA



# max element from the whole 2-D array
arrayB.max()

# if axis=1, it gives column wise maximum
arrayB.max(axis=1)
arrayB.min(axis=0)

array([3, 2])

In [38]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saikumarvellanki/fake-retail-sales-dataset10000-rows")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'